# fly.toml file for s-c-a-m-ibwkya

app = "s-c-a-m-ibwkya"

primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  exercise_api_url = "https://exercisedb-api.vercel.app/api/v1/exercises"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.tcp_checks]
    interval = 10000       # Check every 10 seconds
    timeout = 2000         # Timeout after 2 seconds
    grace_period = 30000   # 30 seconds grace period before checking
    restart_limit = 0      # No limit on restarts
